from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import controller

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1181, 701))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1181, 681))
        self.label.setStyleSheet("border : 1px solid red;")
        self.label.setText("")
        self.label.setObjectName("label")

        self.bgImg=QtGui.QPixmap("login1.jpg")
        self.bgImg=self.bgImg.scaledToHeight(self.label.height())
        self.bgImg=self.bgImg.scaledToWidth(self.label.width())
        self.label.setPixmap(self.bgImg)

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(210, 260, 241, 91))
        self.label_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(420, 480, 381, 111))
        self.pushButton.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(580, 270, 441, 71))
        self.comboBox.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(300, 70, 641, 71))
        self.label_3.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1181, 681))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(390, 70, 141, 91))
        self.label_4.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(540, 70, 301, 91))
        self.label_5.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(170, 200, 291, 91))
        self.label_6.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(170, 330, 291, 91))
        self.label_7.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(560, 210, 451, 81))
        self.lineEdit.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(560, 330, 451, 81))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 520, 291, 81))
        self.pushButton_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1181, 691))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(430, 10, 281, 61))
        self.label_8.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setGeometry(QtCore.QRect(40, 110, 1131, 491))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(5, item)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1181, 681))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(410, 20, 331, 61))
        self.label_9.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(120, 110, 391, 61))
        self.label_10.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(120, 190, 391, 61))
        self.label_11.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(120, 270, 391, 61))
        self.label_12.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(120, 350, 391, 61))
        self.label_13.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(120, 430, 391, 61))
        self.label_14.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(120, 510, 391, 61))
        self.label_15.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(550, 120, 361, 51))
        self.lineEdit_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(550, 200, 361, 51))
        self.lineEdit_4.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(550, 280, 361, 51))
        self.lineEdit_5.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(550, 520, 361, 51))
        self.lineEdit_6.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_2.setGeometry(QtCore.QRect(550, 360, 361, 51))
        self.comboBox_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_3.setGeometry(QtCore.QRect(550, 440, 361, 51))
        self.comboBox_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 600, 401, 71))
        self.pushButton_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1181, 681))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(90, 50, 381, 51))
        self.label_16.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_4.setGeometry(QtCore.QRect(620, 50, 401, 61))
        self.comboBox_4.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(90, 170, 281, 51))
        self.label_17.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(350, 170, 261, 51))
        self.label_18.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(620, 160, 401, 51))
        self.lineEdit_7.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(60, 370, 1051, 271))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 260, 311, 71))
        self.pushButton_4.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1181, 681))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(90, 30, 241, 51))
        self.label_19.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(400, 30, 351, 61))
        self.lineEdit_8.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setGeometry(QtCore.QRect(850, 30, 281, 61))
        self.pushButton_5.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_3.setGeometry(QtCore.QRect(40, 190, 361, 291))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_4.setGeometry(QtCore.QRect(430, 190, 341, 291))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(4, 0, item)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_5.setGeometry(QtCore.QRect(790, 190, 341, 291))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(2)
        self.tableWidget_5.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 0, item)
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(260, 530, 211, 61))
        self.label_20.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setGeometry(QtCore.QRect(790, 530, 281, 61))
        self.pushButton_6.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(490, 530, 211, 61))
        self.label_21.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 31))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuEmployee_Operations = QtWidgets.QMenu(self.menubar)
        self.menuEmployee_Operations.setObjectName("menuEmployee_Operations")
        self.menuEmp_Salary = QtWidgets.QMenu(self.menubar)
        self.menuEmp_Salary.setObjectName("menuEmp_Salary")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAdd_Employee = QtWidgets.QAction(MainWindow)
        self.actionAdd_Employee.setObjectName("actionAdd_Employee")
        self.actionSearch_Employee = QtWidgets.QAction(MainWindow)
        self.actionSearch_Employee.setObjectName("actionSearch_Employee")
        self.actionShow_Employee = QtWidgets.QAction(MainWindow)
        self.actionShow_Employee.setObjectName("actionShow_Employee")
        self.actionUpdate_Employee = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Employee.setObjectName("actionUpdate_Employee")
        self.actionPay_Salary = QtWidgets.QAction(MainWindow)
        self.actionPay_Salary.setObjectName("actionPay_Salary")
        self.menuOptions.addAction(self.actionLogin)
        self.menuOptions.addAction(self.actionRegister)
        self.menuOptions.addAction(self.actionQuit)
        self.menuEmployee_Operations.addAction(self.actionAdd_Employee)
        self.menuEmployee_Operations.addAction(self.actionSearch_Employee)
        self.menuEmployee_Operations.addAction(self.actionShow_Employee)
        self.menuEmployee_Operations.addAction(self.actionUpdate_Employee)
        self.menuEmp_Salary.addAction(self.actionPay_Salary)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuEmployee_Operations.menuAction())
        self.menubar.addAction(self.menuEmp_Salary.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Login As"))
        self.pushButton.setText(_translate("MainWindow", "Login Now"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Admin"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Employee"))
        self.label_3.setText(_translate("MainWindow", "Employee Management System"))
        self.label_4.setText(_translate("MainWindow", "Login As"))
        self.label_5.setText(_translate("MainWindow", "Employee"))
        self.label_6.setText(_translate("MainWindow", "Enter ID"))
        self.label_7.setText(_translate("MainWindow", "Enter Password"))
        self.pushButton_2.setText(_translate("MainWindow", "Login Now"))
        self.label_8.setText(_translate("MainWindow", "Employees Table"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Emp ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Emp Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Emp Dept"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Emp Salary"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Emp Designation"))
        self.label_9.setText(_translate("MainWindow", "Register Employee"))
        self.label_10.setText(_translate("MainWindow", "Enter Email ID"))
        self.label_11.setText(_translate("MainWindow", "Enter Password"))
        self.label_12.setText(_translate("MainWindow", "Enter Name"))
        self.label_13.setText(_translate("MainWindow", "Enter Department"))
        self.label_14.setText(_translate("MainWindow", "Enter Designation"))
        self.label_15.setText(_translate("MainWindow", "Enter Basic Salary"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "IT"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "HR"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Sales"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Marketing"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Finance"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Analyst"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Developer"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Manager"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Project Manager"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Sales Head"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Tester"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Team Lead"))
        self.pushButton_3.setText(_translate("MainWindow", "Register Employee"))
        self.label_16.setText(_translate("MainWindow", "Search Employee By"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "ID"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Name"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Department"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Designation"))
        self.label_17.setText(_translate("MainWindow", "Enter Employee"))
        self.label_18.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Emp ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Emp Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Emp Dept"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Emp Designation"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Emp Salary"))
        self.pushButton_4.setText(_translate("MainWindow", "Search"))
        self.label_19.setText(_translate("MainWindow", "Enter Emp ID"))
        self.pushButton_5.setText(_translate("MainWindow", "Generate Slip"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Emp ID"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Emp Name"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Emp Dept"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Emp Designation"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Basic Salary"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Details"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Earnings"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Actual"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(0, 0)
        item.setText(_translate("MainWindow", "Basic Salary"))
        item = self.tableWidget_4.item(1, 0)
        item.setText(_translate("MainWindow", "HRA"))
        item = self.tableWidget_4.item(2, 0)
        item.setText(_translate("MainWindow", "TA"))
        item = self.tableWidget_4.item(3, 0)
        item.setText(_translate("MainWindow", "CA"))
        item = self.tableWidget_4.item(4, 0)
        item.setText(_translate("MainWindow", "Total"))
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Deductions"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.item(0, 0)
        item.setText(_translate("MainWindow", "TDS"))
        item = self.tableWidget_5.item(1, 0)
        item.setText(_translate("MainWindow", "PF"))
        item = self.tableWidget_5.item(2, 0)
        item.setText(_translate("MainWindow", "Others"))
        item = self.tableWidget_5.item(3, 0)
        item.setText(_translate("MainWindow", "Total"))
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.label_20.setText(_translate("MainWindow", "Net Salary"))
        self.pushButton_6.setText(_translate("MainWindow", "Pay Salary"))
        self.menuOptions.setTitle(_translate("MainWindow", "Login"))
        self.menuEmployee_Operations.setTitle(_translate("MainWindow", "Employee Operations"))
        self.menuEmp_Salary.setTitle(_translate("MainWindow", "Emp Salary"))
        self.actionLogin.setText(_translate("MainWindow", "Employee"))
        self.actionRegister.setText(_translate("MainWindow", "Admin"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAdd_Employee.setText(_translate("MainWindow", "Add Employee"))
        self.actionSearch_Employee.setText(_translate("MainWindow", "Search Employee"))
        self.actionShow_Employee.setText(_translate("MainWindow", "Show Employee"))
        self.actionUpdate_Employee.setText(_translate("MainWindow", "Update Employee"))
        self.actionPay_Salary.setText(_translate("MainWindow", "Pay Salary"))

        self.frame.show()
        self.frame_2.hide()
        # self.frame.show()
        # self.frame_2.hide()
        # self.frame_5.hide()
        # self.frame_5.show()
        # self.frame_6.hide()
        # # self.frame_6.show()

        self.pushButton.clicked.connect(self.showLogin)
        self.pushButton_2.clicked.connect(self.loginUser)
        self.pushButton_3.clicked.connect(self.emp_register)
        self.pushButton_4.clicked.connect(self.search_emp)
        self.pushButton_5.clicked.connect(self.gen_Sal)
        #self.pushButton_6.clicked.connect(None)
        self.comboBox_4.currentTextChanged.connect(self.selectsearchbase)

        self.actionAdd_Employee.triggered.connect(self.showRegister)
        self.actionQuit.triggered.connect(quit)
        self.actionSearch_Employee.triggered.connect(self.show_Search)
        self.actionShow_Employee.triggered.connect(self.loggedIn)
        self.actionPay_Salary.triggered.connect(self.show_sal)

    def selectsearchbase(self,value):
        self.label_18.setText(value)

    def showLogin(self):
        self.frame_2.show()
        self.frame_3.hide()
        LoginAs = self.comboBox.currentText()
        self.label_5.setText(LoginAs)

    def showRegister(self):
        self.frame_4.show()
        self.frame_5.hide()

    def show_Search(self):
        self.frame_4.show()
        self.frame_5.show()
        self.frame_6.hide()
        

    def loginUser(self):
        id = self.lineEdit.text()
        pwd = self.lineEdit_2.text()
        if id == "" or pwd == "":
            QMessageBox.about(self, "Warning","Please Fill all the boxes")
        else:
            data=controller.login(id, pwd)
            if isinstance(data, str):
                QMessageBox.about(self, "Status","Login Failed")
            else:
                self.loggedIn()

    def loggedIn(self):
        self.frame_3.show()
        self.frame_4.hide()
        data=controller.employeedata()
        #print(data)
        self.tableWidget.setRowCount(len(data))
        for i in range(len(data)):
            for j in range(len(data[i])):
                item=QtWidgets.QTableWidgetItem()
                self.tableWidget.setItem(i,j,item)
                item.setText(str(data[i][j]))


    def emp_register(self):
        try:
            email=self.lineEdit_3.text()
            password=self.lineEdit_4.text()
            name=self.lineEdit_5.text()
            department=self.comboBox_2.currentText()
            designation=self.comboBox_3.currentText()
            sal=self.lineEdit_6.text()
            controller.emp_register(email,password,name,department,designation,sal)

            email = self.lineEdit_3.setText("")
            password = self.lineEdit_4.setText("")
            name = self.lineEdit_5.setText("")
            department = self.comboBox_2.currentText()
            designation = self.comboBox_3.currentText()
            sal = self.lineEdit_6.setText("")
            self.showLogin()
        except BaseException as ex:
            print(ex)


    def search_emp(self):
        self.frame.show()
        self.frame_2.show()
        self.frame_3.show()
        self.frame_4.show()
        self.frame_5.show()
        self.frame_6.hide()

        try:
            obj = self.comboBox_4.currentText()
            input = self.lineEdit_7.text()
            data = controller.search_emp(obj, input)
            self.tableWidget_2.setRowCount(len(data))
            for i in range(len(data)):
                for j in range(len(data[i])):
                    item = QtWidgets.QTableWidgetItem()
                    self.tableWidget_2.setItem(i, j, item)
                    item.setText(str(data[i][j]))
        except BaseException as ex:
            print(ex)

    def show_sal(self):
        self.frame_4.show()
        self.frame_5.show()
        self.frame_6.show()
        self.lineEdit_8.setText("")

    def gen_Sal(self):
        try:
            id=self.lineEdit_8.text()
            if id == "":
                QMessageBox.about(self, "Warning","Please Fill the employee id")
            else:
                data=controller.gen_Sal(id)
                if isinstance(data, str):
                    QMessageBox.about(self, "Status", "Employee Id not found")
                else:
                    self.tableWidget_3.setRowCount(len(data))
                    for i in range(len(data)):
                        for j in len(data[i]):
                            item = QtWidgets.QTableWidgetItem()
                            self.tableWidget_3.setItem(i,j, item)
                            item.setText(str(data[i]))
        except BaseException as ex:
            print(ex)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
